server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800 # default

spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/monatium-darknet
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  web:
    resources:
      encoding:
        charset: UTF-8 # 정적 리소스 기본 인코딩 설정
      chain:
        enabled: true # 리소스 체인 기능 활성화
        strategy:
          content:
            enabled: true # 캐시 무효화를 위해 쿼리 스트링에 버전 정보 추가

logging.level:
  org.hibernate.SQL: debug # show executed SQL
  org.hibernate.resource.transaction: debug # show transaction (commit, rollback)
  org.springframework.orm.jpa.JpaTransactionManager: debug
  org.hibernate.orm.jdbc.bind: trace # show binding parameter

# file path (local, for test)
file:
  dir: D:/Dev/trickcal_unofficial/files/
  tempDir: temp/
  noticeDir: imgs/notice/

url:
  character:
    stat:
      personality:
        pure: /imgs/wiki/icons/personality_pure.webp
        madness: /imgs/wiki/icons/personality_madness.webp
        cool: /imgs/wiki/icons/personality_cool.webp
        gloomy: /imgs/wiki/icons/personality_gloomy.webp
        activity: /imgs/wiki/icons/personality_activity.webp

      role:
        dealer: /imgs/wiki/icons/class_dealer.webp
        tanker: /imgs/wiki/icons/class_tanker.webp
        supporter: /imgs/wiki/icons/class_supporter.webp

      attackType:
        physical: /imgs/wiki/icons/normalAttack_physical.webp
        magical: /imgs/wiki/icons/normalAttack_magical.webp

      position:
        front: /imgs/wiki/icons/position_front.webp
        middle: /imgs/wiki/icons/position_middle.webp
        back: /imgs/wiki/icons/position_back.webp
        all: /imgs/wiki/icons/position_all.webp
