server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800 # default

spring:
  profiles:
    active: dev # local
  messages:
    basename: messages, errors

  datasource:
    url: jdbc:h2:tcp://localhost/~/monatium-darknet
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  web:
    resources:
      encoding:
        charset: UTF-8 # 정적 리소스 기본 인코딩 설정
      chain:
        enabled: true # 리소스 체인 기능 활성화
        strategy:
          content:
            enabled: true # 캐시 무효화를 위해 쿼리 스트링에 버전 정보 추가

logging.level:
  org.hibernate.SQL: debug # show executed SQL
  org.hibernate.resource.transaction: debug # show transaction (commit, rollback)
  org.springframework.orm.jpa.JpaTransactionManager: debug
  org.hibernate.orm.jdbc.bind: trace # show binding parameter

# file path (local, for test)
file:
  dir: D:/Dev/trickcal_unofficial/files/
  tempDir: temp/
  noticeDir: imgs/notices/
  wikiDir: imgs/wiki/
  iconDir: imgs/wiki/icons/
  chDir: imgs/wiki/characters/
  asideDir: imgs/wiki/asides/
  spellCardDir: imgs/wiki/cards/spell/
  artifactCardDir: imgs/wiki/cards/artifact/
  skinDir: imgs/wiki/skins/
  defaultThumbnail: /imgs/defaultThumbnail.png

url:
  api_baseUrl: /api/

