# 정적 리소스 동기화 action
name: Deploy Static Resources (via sftp)

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LFTP
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Decode and Setup SSH Key for SFTP
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_SSH_SK_B64 }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SFTP_PORT }} -H ${{ secrets.SFTP_HOST }} >> ~/.ssh/known_hosts

      - name: Upload static resources via SFTP
        run: |
          echo "Hello, SFTP Test!" > hello.txt
          lftp -c "
          set sftp:connect-program 'ssh -a -x -i ~/.ssh/id_rsa -p ${{ secrets.SFTP_PORT }}';
          open -u ${{ secrets.SFTP_USER }}, sftp://${{ secrets.SFTP_HOST }};
          put -O ~/ hello.txt;
          bye
          "


